from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import os

driver = webdriver.Chrome()

driver.get("https://bookshelf.alif.tj/admin/auth/login")

driver.set_window_size(1800, 1200)
time.sleep(2)


email_form = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/label[1]/input[1]")
email_form.send_keys("comifaf244@naymedia.com")
time.sleep(1)
password_form = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/label[1]/input[1]")
password_form.send_keys("A&8b7c6dsh")
time.sleep(1)

submit_button = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/form[1]/button[1]")

submit_button.click()
time.sleep(1)
menu_button = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[2]/nav[1]/a[2]")
menu_button.click()
time.sleep(2)
add_book = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[2]/button[1]")
add_book.click()
time.sleep(2)

element4 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[1]/div[2]/label[1]/input[1]")
current_dir = os.path.abspath(os.path.dirname(__file__))
file_path = os.path.join(current_dir, 'photo.img')
element4.send_keys(file_path)
element5 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[2]/label[1]/input[1]")
element5.send_keys("Book name")
element6 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[3]/label[1]/input[1]")
element6.send_keys("Title")
element7 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[4]/label[1]/input[1]")
element7.send_keys("788")
element8 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[5]/label[1]/input[1]")
element8.send_keys("88888")
element9 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[6]/div[1]/div[1]")
element9.click()
element10 = driver.find_element(By.XPATH, "//div[contains(text(),'Roosevelt Osinski')]")
element10.click()
element11 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[7]/div[1]/div[1]")
element11.click()
element12 = driver.find_element(By.XPATH, "//div[contains(text(),'Нон-фикшн')]")
element12.click()
element13 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[8]/div[1]/div[1]/label[1]/input[1]")
element13.click()
element14 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[8]/div[1]/div[1]/div[1]/div[2]")
element14.click()
element15 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[2]/form[1]/div[8]/div[1]/div[1]/div[1]/div[1]/label[1]/input[1]")
element15.send_keys("55")
element16 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[2]/div[2]/div[3]/button[1]")
element16.click()
time.sleep(2)
menu_button3 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[2]/nav[1]/a[3]")
menu_button3.click()
# menu_element1 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]")
# menu_element1.click()
menu_element2 = driver.find_element(By.XPATH, "//div[contains(text(),'Истаравшан')]")
menu_element2.click()
menu_element3 = driver.find_element(By.XPATH, "///div[contains(text(),'Истаравшан')]")
menu_element3.click()
menu_element4 = driver.find_element(By.XPATH, "//div[contains(text(),'Худжанд')]")
menu_element4.click()
menu_element5 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/div[1]/button[5]")
menu_element5.click()
menu_element6 = driver.find_element(By.XPATH, "//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]")
menu_element6.click()